#! /usr/bin/php
<?php
/**
 * our target cli {command $ php make:controller controllerName} or similar
 * get the argument from controller by $argv as array
 * count the argument by $argc
 * example: $ php hello.php foo loo
 * here $argv[0] = hello.php, $argv[1] = foo so on.
 */
/**
 * At first check more than one one argument
 */
if($argc == 2 && $argv[0]=='fast' && $argv[1]=="-v"){
    echo "\nFast Framework Generator v 1.0.0\n\n";
    exit;
}

include 'system/fast/index.php';