#! /usr/bin/php
<?php
/**
 * our target cli {command $ php make:controller controllerName} or similar
 * get the argument from controller by $argv as array
 * count the argument by $argc
 * example: $ php hello.php foo loo
 * here $argv[0] = hello.php, $argv[1] = foo so on.
 */
/**
 * At first check more than one one argument
 */
if($argc == 1 && $argv[0]=='fast'){
	echo "\n************************************\n";
	echo "* Fast Framework Generator v 1.3.0 *\n";
	echo "************************************\n\n";
	echo "*********** Available Command **********\n";
    echo "* php fast make:controller {controllername}\n";
    echo "* php fast make:model {modelname}\n";
    echo "*****************************************\n\n";
    exit;
}
if($argc == 2 && $argv[0]=='fast' && $argv[1]=="serve"){
    echo "\nDevelopment Project server Started\n";
    echo "Url: localhost:8080\n";
    echo "Press ctrl+c to Exit.\n";
    exec('php -S localhost:8080');
    exit;

}
if($argc == 2 && $argv[0]=='fast' && $argv[1]=="-v"){
    echo "\nFast Framework Generator v 1.3.0\n\n";
    exit;
}

include 'system/fast/index.php';
